import type { Discovery } from './content';

/** Source-reviewed public project descriptions, 18 September 2026. No participant data or inferred clinical outcomes. */
export const RESEARCH_POSTERS: Discovery[] = [
  { id: 'glucose-livia', landmark: 'glucose', title: 'From experience to open science', category: 'LIVIA & GLUCOSEDAO', body: 'Livia Zaharia founded GlucoseDAO to explore glucose prediction through open-source tools. Her work connects lived experience, scientific collaboration, machine learning and usable design. This pavilion brings that research into Livistone: follow the posters from a shared data language to forecasting models and a game about human prediction. The architecture is a new Livistone interpretation.', links: [{ label: 'Livia’s biography', url: 'https://github.com/GlucoseDAO/livia/blob/main/content/biography.md' }, { label: 'Explore GlucoseDAO repositories', url: 'https://github.com/GlucoseDAO' }] },
  { id: 'glucose-game', landmark: 'glucose', title: 'Sugar-Sugar', category: '01 / HUMAN PREDICTION', body: 'GlucoseDAO built a browser game in which people predict the continuation of a glucose trace. It makes human forecasting something that can be explored and compared with model predictions. The open repository contains the application and its study workflows. The game and its research questions are distinct from published study results; this display does not claim that people or models have won.', links: [{ label: 'Sugar-Sugar repository', url: 'https://github.com/GlucoseDAO/sugar-sugar' }] },
  { id: 'glucose-format', landmark: 'glucose', title: 'A shared language for data', category: '02 / DATA FOUNDATIONS', body: 'Different glucose sensors export different files. The cgm_format project converts common continuous glucose monitoring exports into a unified format for machine learning. A companion data-processing repository prepares research datasets. These public tools make a practical contribution: they let researchers work with consistent inputs before training or comparing models.', links: [{ label: 'cgm_format repository', url: 'https://github.com/GlucoseDAO/cgm_format' }, { label: 'Data-processing repository', url: 'https://github.com/GlucoseDAO/glucose_data_processing' }] },
  { id: 'glucose-models', landmark: 'glucose', title: 'Learning possible futures', category: '03 / FORECASTING RESEARCH', body: 'The glucose-forecasting repository brings together training and evaluation for several model families. GluMind combines glucose with heart rate and steps; SugarOne uses glucose, insulin and carbohydrate inputs. Shared evaluation tools support comparisons with baseline models. These are research systems: results depend on the dataset and evaluation setup, and are not a promise about an individual’s future glucose.', links: [{ label: 'Forecasting repository and evaluations', url: 'https://github.com/GlucoseDAO/glucose-forecasting' }, { label: 'Earlier NeuralForecast experiments', url: 'https://github.com/GlucoseDAO/glucose-neuralforecast' }] },
  { id: 'glucose-service', landmark: 'glucose', title: 'From models to tools', category: '04 / OPEN INFRASTRUCTURE', body: 'The gluRPC project exposes glucose prediction through a gRPC service. Together with data converters, forecasting code and Sugar-Sugar, it forms part of a public software ecosystem that others can inspect and build on. Livistone displays this work as an exhibition; it does not collect glucose readings, run a prediction service or provide treatment advice.', links: [{ label: 'gluRPC repository', url: 'https://github.com/GlucoseDAO/gluRPC' }] },
  { id: 'glucose-molecule', landmark: 'glucose', title: 'A molecule becomes a place', category: 'INSULIN / PDB 1TRZ', body: 'The two overhead ribbons follow the alpha-carbon coordinates of human insulin chains A and B from PDB entry 1TRZ: 21 and 30 residues. Gold connectors mark its three disulfide bonds. The small glucose sculpture uses the ideal heavy-atom coordinates of alpha-D-glucopyranose, component GLC. Scaling, supports and the open gallery are architectural inventions; these are different molecules, not interchangeable names.', links: [{ label: 'Human insulin structure · 1TRZ', url: 'https://www.rcsb.org/structure/1TRZ' }, { label: 'Alpha-D-glucopyranose · GLC', url: 'https://www.rcsb.org/ligand/GLC' }] },
];
