import type { Discovery } from './content';

export interface ResearchSlide { title: string; body: string; image?: string; imageAlt?: string }
const POSTER = 'https://drive.google.com/file/d/1lzwvasgtLLSQ7X4qh5xixGZRhWFZVcLu/view';
const TEXT = 'https://docs.google.com/document/d/1BILbcqv7yr4_gb3Plmm5Q9FiPMVUzjpsyFXTnP2hgb8/edit';
const KYIV = 'https://docs.google.com/presentation/d/1KJa-wgU9ljGFznFV_s3Cy3HhU2P870M5E9kuZA7T-xI/edit';
const TALK = 'https://docs.google.com/presentation/d/1SrdHJ4IVZIFiRDoj3VDkZFOp5AtTET_kvtZsSyLrQmQ/edit';
const links = [{ label: 'Predicting Glucose Before It Happens · original slides', url: TALK }, { label: 'Original Romanian AI Days 2026 poster', url: POSTER }, { label: 'Glucose text · source folder', url: TEXT }, { label: 'Kyiv 2026 talk slides', url: KYIV }];
const picture = (name: string): string => '/images/research/' + name + '.webp';
const original: ResearchSlide = { title: 'The original poster', body: 'Livia Zaharia and collaborators · Romanian AI Days, 18–19 September 2026, Politehnica Bucharest. These are the authors’ reported research results; the poster states that prospective validation remains necessary.', image: picture('original-poster'), imageAlt: 'Complete original poster: Predicting glucose, personalizing models' };

/** Text and unredrawn image extracts from the supplied Drive folder; see public/images/research/ATTRIBUTION.md. */
export const RESEARCH_POSTERS: (Discovery & { slides: ResearchSlide[] })[] = [
  { id: 'glucose-livia', landmark: 'glucose', title: 'Why glucose matters', category: '01 / READING THE CURVE', links,
    body: 'A continuous glucose monitor shows a changing curve across the day. Livia’s original presentation connects those curves to everyday life; the research poster asks how the next hour might be forecast. Images and text here are extracted from both sources in the supplied Drive folder.',
    slides: [{ title: 'A curve through the day', body: 'The source poster labels these traces as illustrative, not measured data. It describes a forecast as an estimate of the next hour and distinguishes research comparisons from clinical validation.', image: picture('cgm'), imageAlt: 'Original poster section: What is a CGM, illustrative traces, and why forecast glucose' }, original] },
  { id: 'glucose-format', landmark: 'glucose', title: 'How glucose is measured', category: '02 / CGM AND INPUTS', links,
    body: 'The poster describes a coin-sized sensor and transmitter worn on the arm, reporting glucose every five minutes. Its forecasting comparisons use that five-minute grid: twelve future readings make one hour.',
    slides: [{ title: 'From sensor to a time series', body: 'The original CGM panel cites Dexcom G6 Pro and Houston Endocrine Center. The poster describes the sensor stream, then illustrates two different daily curves.', image: picture('cgm'), imageAlt: 'CGM explanation and glucose traces from Livia Zaharia’s original poster' }, { title: 'What do insulin and meals add?', body: 'This source panel compares removing inputs from SugarOne on Loop T1D. It reports increases in MAE relative to all inputs. These are the authors’ model experiments.', image: picture('inputs'), imageAlt: 'Original ablation chart showing glucose-only, no-bolus, no-carbohydrate and no-basal comparisons' }] },
  { id: 'glucose-service', landmark: 'glucose', title: 'GlucoseDAO', category: '03 / OPEN RESEARCH', links,
    body: 'The supplied “glucose text” describes SugarGenie as a chatbot combining LLM agents, semantic search and indexed scientific papers. It pairs that work with Sugar-Sugar, a game for studying human glucose prediction. The 2026 poster presents the forecasting research.',
    slides: [{ title: 'Models, data and public exploration', body: 'The poster introduces open data, Sugar I, SugarOne, SugarJEPA and the Sugar-Sugar human benchmark. The accompanying source text describes interactive health-data exploration through SugarGenie and Sugar-Sugar.', image: picture('original-poster'), imageAlt: 'GlucoseDAO’s original Romanian AI Days 2026 poster' }, { title: 'Inside the research architecture', body: 'The original diagram shows a 24-hour JEPA encoder supplying a token to a 128-step SugarOne backbone. Its labels and connections are reproduced directly from the poster.', image: picture('architecture'), imageAlt: 'Original SugarJEPA architecture diagram with encoder and SugarOne backbone' }] },
  { id: 'glucose-game', landmark: 'glucose', title: 'Sugar-Sugar', category: '04 / TRY THE NEXT HOUR', links: [...links, { label: 'Play Sugar-Sugar', url: 'https://sugar-sugar.study/' }],
    body: 'See three hours of CGM history, draw the next hour, and compare your prediction with what happened. The original poster invites visitors to help build the human baseline. Its recruitment numbers are a dated snapshot from 5 September 2026.',
    slides: [{ title: 'Try glucose forecasting yourself', body: 'The original panel includes the game link, study contact information and consent notice. It says completion takes approximately 6–12 tasks and that human-versus-AI results are not yet established.', image: picture('sugar-sugar'), imageAlt: 'Original Sugar-Sugar invitation, QR code and study information' }, original] },
  { id: 'glucose-models', landmark: 'glucose', title: 'Learning possible futures', category: '05 / MODELS AND PERSONALISATION', links,
    body: 'The poster compares forecasting models on global holdout data and examines personalisation. Its central observation is that personalisation can help or hurt: the starting model and training budget matter. These are reported research comparisons.',
    slides: [{ title: 'The original model diagram', body: 'SugarJEPA architecture from the supplied poster, including the JEPA encoder, cross-attention and SugarOne backbone.', image: picture('architecture'), imageAlt: 'SugarJEPA architecture from the original research poster' }, { title: 'Global holdout comparisons', body: 'The authors compare MAE, RMSE and MARD on an AI-READI + Loop test split. This image preserves their table, footnotes and preliminary 120-minute forecast comparison.', image: picture('benchmarks'), imageAlt: 'Original global holdout benchmark table and forecast chart' }, { title: 'Personalisation can help — or hurt', body: 'The source follows seven people with T1D, with fixed chronological validation and test sets. It cautions that mean improvements do not guarantee improvement for each person.', image: picture('personalisation'), imageAlt: 'Original personalisation plots across training budgets' }] },
  { id: 'glucose-molecule', landmark: 'glucose', title: 'A molecule becomes a place', category: '06 / MOLECULES AND MEASUREMENTS', links: [...links, { label: 'Human insulin · PDB 1TRZ', url: 'https://www.rcsb.org/structure/1TRZ' }, { label: 'Glucose · GLC', url: 'https://www.rcsb.org/ligand/GLC' }],
    body: 'The overhead ribbons follow human insulin, PDB 1TRZ. The smaller glowing sculpture is glucose, GLC. They are different molecules. The source poster’s input study connects the exhibition to the measurements used by forecasting models.',
    slides: [{ title: 'Insulin, glucose and model inputs', body: 'The pavilion uses the deposited insulin fold and separate glucose atom coordinates. The image is the original poster’s insulin-and-meals input study, not a drawing of either molecule.', image: picture('inputs'), imageAlt: 'Original poster: What do insulin and meals add?' }, original] },
];

const talkSlide = (page: number, title: string, body: string): ResearchSlide => ({ title, body: body + ` Original presentation, slide ${page}.`, image: picture('slide-' + String(page).padStart(2, '0')), imageAlt: `Original presentation slide ${page}: ${title}` });
const talkChapters: ResearchSlide[][] = [
  [talkSlide(1, 'Predicting Glucose Before It Happens', 'Livia introduces open, device-agnostic models for continuous glucose data and the work of building them in the open.'), talkSlide(3, 'A day seen through glucose', 'The presentation connects a daily glucose trace to meals, hunger and the experience of wearing a CGM. This is the author’s illustrated example.')],
  [talkSlide(2, 'The sensor and transmitter', 'The original slide shows an arm-worn sensor, an insertion sequence and a cross-section through the skin. Its references are retained in the image.'), talkSlide(9, 'The shape of a response', 'The talk cites research about variation in post-meal glucose curves. The reproduced slide retains the cited papers and figures; it is presented as research context.')],
  [talkSlide(12, 'From data to an API', 'The source diagram connects training datasets, a foundational glucose model, fine-tuning and apps through an API. It is a diagram of the project’s research direction.'), talkSlide(13, 'People behind the project', 'The original deck introduces the team and scientific advisory board as listed in September 2026.')],
  [talkSlide(14, 'Human forecasting in Sugar-Sugar', 'The source introduces a study comparing human glucose predictions with machine-learning models. See the original game screenshots and study invitation.'), talkSlide(16, 'Ask Sugar-genie', 'The closing slide invites collaborators and medical centres for clinical testing, and directs questions to Sugar-genie and the team.')],
  [talkSlide(15, 'Forecasts in the original talk', 'These plots and performance statements are the authors’ reported results from the presentation. They are separate from the more detailed poster benchmarks and are not independent clinical validation.')],
  [talkSlide(11, 'The everyday setting', 'A photographic slide connects GlucoseDAO to daily life and food. The architecture outside this panel uses separate deposited molecular coordinates; the talk photographs are not molecular models.')],
];
RESEARCH_POSTERS.forEach((chapter, index) => { chapter.slides.unshift(...talkChapters[index]); });
